
import { IGenerator, ProjectConfig, GeneratorOutput, GeneratedFile } from './interfaces';

export abstract class BaseGenerator implements IGenerator {
  abstract generate(config: ProjectConfig): Promise<GeneratorOutput>;

  protected createFile(path: string, content: string): GeneratedFile {
    return { path, content };
  }

  protected getCommonFiles(config: ProjectConfig): GeneratedFile[] {
    const files = [
      {
        path: 'README.md',
        content: `# ${config.projectName}\n\n${config.description || 'Generated by Software Factory AI'}\n\n## Getting Started\nSee specific instructions below.`
      },
      {
        path: '.gitignore',
        content: `node_modules/\n.env\n.DS_Store\ndist/\nbuild/\n`
      }
    ];

    if (config.license === 'proprietary') {
      files.push({
        path: 'LEGAL_NOTICE.md',
        content: `# Proprietary Software\n\nCopyright (c) ${new Date().getFullYear()} ${config.projectName}\n\nAll rights reserved. This software is confidential and proprietary information of the owner.\nUnauthorized copying of this file, via any medium is strictly prohibited.`
      });
    } else {
      // Default to MIT
      files.push({
        path: 'LICENSE',
        content: `MIT License\n\nCopyright (c) ${new Date().getFullYear()} ${config.projectName}\n\nPermission is hereby granted, free of charge, to any person obtaining a copy\nof this software and associated documentation files (the "Software"), to deal\nin the Software without restriction, including without limitation the rights\nto use, copy, modify, merge, publish, distribute, sublicense, and/or sell\ncopies of the Software, and to permit persons to whom the Software is\nfurnished to do so, subject to the following conditions:\n\nThe above copyright notice and this permission notice shall be included in all\ncopies or substantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\nFITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\nAUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\nLIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\nOUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\nSOFTWARE.`
      });
    }

    return files;
  }
}
