import { IGenerator, ProjectConfig, GeneratorOutput, GeneratedFile } from '../interfaces';

export abstract class BaseGenerator implements IGenerator {
  abstract generate(config: ProjectConfig): Promise<GeneratorOutput>;

  protected createFile(path: string, content: string): GeneratedFile {
    return { path, content };
  }

  protected getCommonFiles(config: ProjectConfig): GeneratedFile[] {
    return [
      {
        path: 'README.md',
        content: `# ${config.projectName}\n\n${config.description || 'Generated by Software Factory AI'}\n\n## Getting Started\nSee specific instructions below.`
      },
      {
        path: '.gitignore',
        content: `node_modules/\n.env\n.DS_Store\ndist/\nbuild/\n`
      }
    ];
  }
}
